name: Test

on:
  workflow_dispatch:
    inputs:
      env:
        description: "input"
        required: true

jobs:
  test:
    if: github.event.inputs.env == "${MATRIX_ENV}" || github.event.inputs.env == 'B'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - env: A
            test: B
          - env: C
            test: D
    env:
      GITHUB_SHA: ${{ github.sha }}
      GITHUB_REF_NAME:  ${{ github.ref_name }}
      MATRIX_ENV: ${{ matrix.env }}
      INPUTS_ENV: ${{ github.event.inputs.env }}
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6
          bundler-cache: true
      - name: echo
        run: |
          echo ${INPUTS_ENV}
          ruby -v
