name: Test

on:
  workflow_dispatch:
    inputs:
      env:
        description: "input"
        required: true

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - env: A
            test: B
          - env: C
            test: D
        test:
          - "OK"
          - "YES"
    env:
      GITHUB_SHA: ${{ github.sha }}
      GITHUB_REF_NAME:  ${{ github.ref_name }}
      ENV: ${{ github.event.inputs.env }}
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6
          bundler-cache: true
      - run: |
          if [[ ${{ matrix.env }} == ${ENV} ]]; then
            echo ${{ matrix.test }}
            ruby -v
          fi
