name: Test

on:
  workflow_dispatch:
    inputs:
      env:
        description: "input"
        required: true
      sha:
        required: false
  push:
    branches:
      - master

jobs:
  test:
    if: contains('A', github.event.inputs.env)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - env: A
            test: B
    env:
      GITHUB_SHA: ${{ github.sha }}
      GITHUB_REF_NAME:  ${{ github.ref_name }}
      MATRIX_ENV: ${{ matrix.env }}
      INPUTS_ENV: ${{ github.event.inputs.env }}
      SHA: ${{ github.events.inputs.sha || github.sha }}
    steps:
      - uses: actions/checkout@v2
      - run: aws --version
      - run: docker --version
      # - uses: ./.github/actions/awscli-v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6
          bundler-cache: true
      - name: echo
        run: |
          echo ${INPUTS_ENV} ${MATRIX_ENV}
          echo ${SHA:-sha}
          ruby -v
          bundler -v
