name: Test

on:
  workflow_dispatch:
    inputs:
      env:
        description: "input"
        required: true
      sha:
        required: false
  workflow_run:
    workflows: [Test on push]
    types:
      - completed

jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - run: echo 'The triggering workflow passed'
  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run: echo 'The triggering workflow failed'
  test:
    runs-on: ubuntu-latest
    env:
      GITHUB_SHA: ${{ github.sha }}
      GITHUB_REF_NAME:  ${{ github.ref_name }}
      GITHUB_REF_TYPE_IS_BRANCH: ${{ github.ref_type == 'branch' }}
      INPUTS_ENV: ${{ github.event.inputs.env || 'test' }}
      SHA: ${{ github.events.inputs.sha || github.sha }}
    steps:
      - uses: actions/checkout@v2
      - run: aws --version
      - run: docker --version
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6
          bundler-cache: true
      - name: test
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: |
          echo "$GITHUB_CONTEXT"
          env
          ruby -v
          bundler -v
